# Generated by Django 5.0.1 on 2024-02-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_telegramuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
